### PR TITLE
Center Title Card

### PR DESCRIPTION
**Pull request by Williamtobs**
This is a widget that shows the title of what is being displayed in the center area and rounded rectangle of avatars and the number of people in the channel. This rounded rectangle may be different from when you are in someone's DM.

To do

- [x] add trailing widget
- [x] add leading title

task screen

### CODE REVIEW

**Review by toxic-bishop — APPROVED** [review]
LGTM

**Comment by Williamtobs** [comment]
task screen

**Review by toxic-bishop — APPROVED** [review]
LGTM

**Review by toxic-bishop — APPROVED** [review]
LGTM

**Review by osobotu — APPROVED** [review]
LGTM

**Pull request merged**
