### PR TITLE
Sign in form

### PR DESCRIPTION
**Pull request by Adevikki**
SignIn
This is the input form that will be used for signIn

### CODE REVIEW

**Review by osobotu — DISMISSED** [review]
LGTM

**Review by developerjamiu — CHANGES_REQUESTED** [review]
Add a screenshot of your implemention

**Review by toxic-bishop — APPROVED** [review]
LGTM

**Comment by Adevikki** [comment]
> Add a screenshot of your implemention

Done

**Review by developerjamiu — APPROVED** [review]

**Review by osobotu — APPROVED** [review]
LGTM

**Review by toxic-bishop — APPROVED** [review]
LGTM

**Pull request merged**
