### PR TITLE
consistent UI throughout the app based on issue #241

### PR DESCRIPTION
**Pull request by osobotu**
The package is `zcdesk_ui` and contains app wide colors and textstyles. Built as a package so that it can be extended as the app grows. 
Can be found in the top level `packages` folder of the app. Solution to #241

### CODE REVIEW

**Review by obidekatherine — APPROVED** [review]
LGTM

**Review by Perpety — COMMENTED** [review]
LGTM

**Review by Perpety — APPROVED** [review]
LGTM

**Comment by osobotu** [comment]
https://user-images.githubusercontent.com/72420125/132060043-b6e7b9bf-dbfd-455f-b89e-97a7291136e6.mp4

Implemented UI package used for building the app so far.

**Pull request merged**
