### PR TITLE
start_dm_with_another_user

### PR DESCRIPTION
**Pull request by ndungudedan**
start dm with another user based on issue #354 

https://user-images.githubusercontent.com/38168632/133250116-0d7c5705-df1e-4c18-867d-e17955825033.mp4

### CODE REVIEW

**Review by demolaf — CHANGES_REQUESTED** [review]
don't make changes to the homeview, if dm view is meant to be triggered by an ontap function from the leftsidebar. just commit the dm view UI. you don't need to make another PR just commit changes to this same one. I'll suggest deleting changes to homeview.dart

**Review by ndungudedan — COMMENTED** [review]
change to home view

**Review by demolaf — APPROVED** [review]

**Review by demolaf — APPROVED** [review]
LGTM.

**Review by Perpety — APPROVED** [review]
LGTM

**Pull request closed without merging**
