### PR TITLE
Todo_UI

### PR DESCRIPTION
**Pull request by Adevikki**
https://user-images.githubusercontent.com/54329332/136789860-476fd565-0bec-47f9-97bc-13ca2641a0f1.mp4

### CODE REVIEW

**Comment by ndungudedan** [comment]
please flutter analyze or check the builds failing..
update your code accordingly
also remove test_helpers_mock.dart..it is a generated file

**Comment by Adevikki** [comment]
> please flutter analyze or check the builds failing.. update your code accordingly also remove test_helpers_mock.dart..it is a generated file

Done that boss

**Review by Codesait — APPROVED** [review]
LGTM

**Review by ndungudedan — APPROVED** [review]
LGTM

**Pull request merged**
