### PR TITLE
setup for stackedLogger

### PR DESCRIPTION
**Pull request by demolaf**
#240 

Setup stackedLogger for detailed logs of events.

### CODE REVIEW

**Review by isaacadariku — APPROVED** [review]
LGTM

**Review by osobotu — APPROVED** [review]
@demolaf Please pull from the dev branch before pushing always to avoid merge conflicts.

**Comment by demolaf** [comment]
> @demolaf Please pull from the dev branch before pushing always to avoid merge conflicts.

alright won't happen again.

**Review by isaacadariku — APPROVED** [review]
LGTM

**Comment by markessien** [comment]
No testing link

**Pull request merged**
